version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=true
      - BYPASS_AUTH=true  # ローカル開発環境での認証バイパス
      - DATABASE_URL=postgresql://postgres:password@db:5432/talknote
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/service-account.json
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=talknote
    ports:
      - "5433:5432"

volumes:
  postgres_data:
